name: educational_app_maquetacion
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/diamonds.png
    - assets/images/music_card.png
    - assets/images/music_card_2.png
    - assets/images/geo_card.png
    - assets/images/find_card.png
    - assets/images/math_logo.png
    - assets/images/science_logo.png
    - assets/images/science_card.png
    - assets/images/geo_logo.png
    - assets/images/music_logo.png
    - assets/images/grammar_logo.png
    - assets/images/grammar_card.png
    - assets/images/clock_card.png
    - assets/images/puzzle_card.png
    - assets/images/search_icon.png

  fonts:
    - family: Roslindale
      fonts:
        - asset: assets/fonts/RoslindaleDeckNarrowBoldTesting.ttf
          weight: 700
        - asset: assets/fonts/RoslindaleDeckNarrowRegularTesting.ttf


