name: educational_app_maquetacion
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/diamonds.png
    - assets/images/music_card.png
    - assets/images/geo_card.png
    - assets/images/find_card.png

  fonts:
    - family: Roslindale
      fonts:
        - asset: assets/fonts/RoslindaleDeckNarrowBoldTesting.ttf
          weight: 700
        - asset: assets/fonts/RoslindaleDeckNarrowRegularTesting.ttf


